# A simple set of sane defaults for connecting to the Ridcully testnet

[base_node]
network = "stibbons"

[base_node.stibbons]
db_type = "lmdb"
enable_mining = false
peer_seeds = [
"b848e32130ff91bbe55a6739e2469548df1288b7c7b9e64e71e2cfb1e5c49e6b::/onion3/qfrr7k7hz6bmnp3frno5ifzqhbodcnef42q46ncjvj4ve3ho6z7qm7ad:18141"
]
grpc_enabled = true
grpc_base_node_address = "127.0.0.1:18142"
grpc_console_wallet_address = "127.0.0.1:18143"
transport = "tor"
dns_seeds =["seeds.stibbons.tari.com"]
dns_seeds_use_dnssec = false
pruning_horizon = 100

[merge_mining_proxy.stibbons]
monerod_url = "http://18.133.55.120:38081"
proxy_host_address = "127.0.0.1:7878"
monerod_use_auth=false
monerod_username=""
monerod_password=""

